spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localdb;DB_CLOSE_DELAY=-1
    username: sa

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibenate:
        format_sql: true
    show-sql: true